### ISSUE TITLE
Promesa 1.1.1 is missing some externs, breaks advanced optimization

### ISSUE THREAD

**Issue by ingesolvoll** [nervous-systems/kvlt#13]
It seems the promesa version referenced by kvlt is missing some needed externs definitions, I'm getting

app.js:953 Uncaught TypeError: Promise.vj is not a function(anonymous function) @ app.js:953

On this code:

var IM,JM=Promise.vj();JM.log(jG,{cancellation:!0,warnings:!1},void 0);

I reported this issue at promesa first, but it turned out that their newest version (1.4.0) worked when my build was configured correctly.  I also tested by having my project directly depend on 1.2.0  of promesa, did not make a difference. Newer versions are not possible, since kvlt is referencing the monad namespace in promesa, which was removed in newer versions.

**Comment by moea** [comment]
Well spotted, thanks - will fix today.

**Comment by ingesolvoll** [comment]
Turns out this is probably not true either, My report here is most likely Promise.noConflict, which was fixed in 1.1.1 of promesa. Sorry, disregard this issue.
