### ISSUE TITLE
Cannot find module 'websocket'

### ISSUE THREAD

**Issue by Hidfeel** [nervous-systems/kvlt#17]
I try to use kvlt in nodejs . I don't need `websocket` , why  should I install  `websocket`

**Comment by moea** [comment]
@Hidfeel If you don't run `lein deps` to install the third-party dependencies, the project will fail elsewhere (e.g. absence of the `request` module, etc.)  If you'd like to submit a patch which makes the websocket dependency optional (e.g. via a lein profile) - that's fine too - but for now, I'd suggest running `lein deps`.

**Comment by vikeri** [comment]
I tried `lein deps` but it still didn't work
