### ISSUE TITLE
Can't view document online

### ISSUE THREAD

**Issue by coldnew** [nervous-systems/kvlt#23]
Seems like there's some problem in https://nervous.io/doc/kvlt server, I have following issue :(

<img width="950" alt="screen shot 2017-02-09 at 1 30 27 pm" src="https://cloud.githubusercontent.com/assets/39703/22770507/0d270e10-eecc-11e6-8289-5a04bf6cfd30.png">

**Comment by moea** [comment]
I've redeployed the docs: https://nervous.io/doc/kvlt/

It may have take a while to work for you if your CloudFront edge server had previously cached the 404.
